In [1]:
import numpy as np
from modules.executor import Executor
from modules.feature import FeatureExtractor
from modules.algorithms.perceptron import Perceptron
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
import copy

## 2. Using Perceptron

In [9]:
perc = Perceptron(10000)
featEx = FeatureExtractor(grid_shape = (2,2), round_off = 2)
execute = Executor(data_source = 'digitdata', featureExtractor=featEx, algorithm=perc, metric = 'acc')

X Shape: (5000, 196), Y Shape: (5000,)


In [3]:
print(execute.train_mean_met)
print(execute.val_mean_met)
print(execute.test_mean_met)

[1.0]
[0.8870431893687708]
[0.88]


In [3]:
X_train = execute.X_train
Y_train = execute.Y_train

perc = Perceptron(10000)

NameError: name 'execute' is not defined

In [9]:
perc.fit(X_train, Y_train)

10 784
(10, 785) (785, 5000)
(5000,) (5000,)
[5 0 4 ... 2 1 2]
[0 0 0 ... 0 0 0]
5000
(10, 785) (785, 5000)
(5000,) (5000,)
[5 0 4 ... 2 1 2]
[3 3 4 ... 2 1 2]
5000
Entered Break
Training ended


In [7]:
print(execute.train_mean_met)
print(execute.val_mean_met)
print(execute.test_mean_met)

[0.288, 0.23000000000000004, 0.31533333333333335, 0.3125, 0.3808, 0.312, 0.6508571428571429, 0.923, 0.6371111111111111, 0.1414]
[0.356, 0.271, 0.363, 0.312, 0.41, 0.293, 0.641, 0.8459999999999999, 0.581, 0.139]
[0.334, 0.262, 0.34, 0.296, 0.387, 0.285, 0.612, 0.8030000000000002, 0.57, 0.125]


## 1. Using Naive Bayes Implementation

In [ ]:
featEx = FeatureExtractor(grid_shape = (5,5), round_off = 1)
nb = NaiveBayes(k = 0.1)
execute = Executor(data_source = 'facedata', featureExtractor=featEx, algorithm=nb, metric = 'acc', quick=False)

In [ ]:
print(execute.train_mean_met)
print(execute.val_mean_met)
print(execute.test_mean_met)

In [ ]:
np.round(0.001, 0)

In [ ]:
featEx = FeatureExtractor(grid_shape = (4,4), round_off = 2)

for k in [0.0001, 0.001, 0.005, 0.01, 0.05, 0.1, 1, 2]:
    nb = NaiveBayes(k)
    execute = Executor(data_source = 'digitdata', featureExtractor=featEx, algorithm=nb, metric = 'acc', quick=True)
    print(execute.test_mean_met)

###### print(execute.train_mean_met)
print(execute.val_mean_met)
print(execute.test_mean_met)

In [ ]:
nb.predict(execute.X_val)

In [ ]:
nb.likelihoods

In [ ]:
np.unique(execute.Y_train)

In [ ]:
execute.X_train

In [ ]:
nb = NaiveBayes(k = 1)

In [ ]:
nb.fit(execute.X_train, execute.Y_train)

In [ ]:
out = nb.predict(execute.X_val)

In [ ]:
nb.y_probs

In [ ]:
out

In [ ]:
np.argmax(out, axis=1)

## 3. Using SVM module from scikit-learn 

### 3.1 Results on Face Data

In [7]:
svc = SVC()
featEx = FeatureExtractor(grid_shape = (2,2), round_off = 2)
execute = Executor(data_source = 'digitdata', featureExtractor=featEx, algorithm=svc, metric = 'acc')

X Shape: (5000, 196), Y Shape: (5000,)


In [8]:
print(execute.train_mean_met)
print(execute.val_mean_met)
print(execute.test_mean_met)

[0.9884]
[0.926]
[0.919]


In [10]:
svc = SVC()
featEx = FeatureExtractor(grid_shape = (10,10), round_off = 2)
execute = Executor(data_source = 'digitdata', featureExtractor=featEx, algorithm=svc, metric = 'acc')

Exception: Grid size incompatible with image dimensions

### Results on Digit Data

In [ ]:
featEx = FeatureExtractor(grid_shape = (4,4), round_off = 2)
svc = SVC()

In [ ]:
execute = Executor(data_source = 'digitdata', featureExtractor=None, algorithm=svc, metric = 'acc')

In [ ]:
print(execute.train_mean_met)
print(execute.val_mean_met)
print(execute.test_mean_met)

In [ ]:
sort_x = np.sort(execute.X_train,axis=0)
unique_feature_counts = (sort_x[1:,:] != sort_x[:-1,:]).sum(axis=0)+1
unique_feature_counts

In [ ]:
np.unique(execute.X_train[:,34])